---
resource_types:
- name: bbl-state-resource
  type: docker-image
  source:
    repository: cfinfrastructure/bbl-state-resource

resources:
- name: source
  type: git
  source:
    uri: ((source-repo.uri))
    private_key: ((source-repo.private_key))

- name: task-image
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3
    tag: latest

- name: credhub-bosh-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/credhub-release

- name: uaa-bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/uaa-release

- name: bbl-state
  type: bbl-state-resource
  source:
    iaas: gcp
    bucket: ((bbl_gcp.bucket))
    gcp_region: ((bbl_gcp.region))
    gcp_service_account_key: ((bbl_gcp.service_account_key))

- name: bbl-cli
  type: github-release
  check_every: 24h
  source:
    owner: cloudfoundry
    repository: bosh-bootloader
    access_token: ((git-access-token))

- name: bosh-cli
  type: github-release
  check_every: 24h
  source:
    owner: cloudfoundry
    repository: bosh-cli
    access_token: ((git-access-token))

jobs:
- name: create-test-env
  plan:
  - aggregate:
    - get: task-image
    - get: bbl-cli
      params:
        globs: ['bbl*linux*']
    - get: bosh-cli
      params:
        globs: ['bosh*linux*']
    - get: source
      trigger: true
    - get: credhub-bosh-release
      trigger: true
    - get: uaa-bosh-release
      trigger: true
    - put: bbl-state
      params:
        command: up
        name: ((bbl_gcp.name))
  - task: deploy-credhub
    image: task-image
    file: source/integration-tests/ci/tasks/deploy-credhub.yml

- name: run-integration-tests
  plan:
  - aggregate:
    # - get: task-image
    - get: source
      trigger: true
      passed: [create-test-env]
    - get: bbl-state

- name: clean-up
  plan:
  - aggregate:
    - get: task-image
    - get: bbl-state
    - get: source
      trigger: true
      passed: [run-integration-tests]
  - task: delete-credhub
    image: task-image
    file: source/integration-tests/ci/tasks/delete-credhub.yml

- name: delete-env
  plan:
  - get: source
    trigger: true
    passed: [clean-up]
  - put: bbl-state
    params:
      command: destroy
      name: ((bbl_gcp.name))
